[package]
name = "ohnotel"
version = "0.1.0"
edition = "2024"

[dependencies]
ordered-float = "5"
opentelemetry-proto = { version = "0.32.0" }

[workspace.lints]
clippy.allow_attributes = "deny"
clippy.as_pointer_underscore = "deny"
clippy.as_underscore = "deny"
clippy.borrow_as_ptr = "deny"
clippy.cast_lossless = "deny"
clippy.cast_possible_truncation = "deny"
clippy.cast_possible_wrap = "deny"
clippy.cast_ptr_alignment = "deny"
clippy.cast_sign_loss = "deny"
clippy.clone_on_ref_ptr = "deny"
clippy.cloned_instead_of_copied = "deny"
clippy.comparison_chain = "deny"
clippy.debug_assert_with_mut_call = "deny"
clippy.elidable_lifetime_names = "deny"
clippy.equatable_if_let = "deny"
clippy.explicit_into_iter_loop = "deny"
clippy.explicit_iter_loop = "deny"
clippy.filter_map_next = "deny"
clippy.flat_map_option = "deny"
clippy.format_collect = "deny"
clippy.format_push_string = "deny"
clippy.ignored_unit_patterns = "deny"
clippy.implicit_clone = "deny"
clippy.inefficient_to_string = "deny"
clippy.items_after_statements = "deny"
clippy.iter_on_empty_collections = "deny"
clippy.iter_on_single_items = "deny"
clippy.iter_with_drain = "deny"
clippy.manual_is_variant_and = "deny"
clippy.manual_let_else = "deny"
clippy.manual_midpoint = "deny"
clippy.match_same_arms = "deny"
clippy.module_name_repetitions = "deny"
clippy.multiple_inherent_impl = "deny"
clippy.needless_pass_by_value = "deny"
clippy.or_fun_call = "deny"
clippy.rc_buffer = "deny"
clippy.redundant_closure_for_method_calls = "deny"
clippy.redundant_pub_crate = "deny"
# clippy.redundant_test_prefix = "deny" # TODO: reengage once supported on stable
clippy.ref_option = "deny"
clippy.ref_option_ref = "deny"
clippy.str_to_string = "deny"
clippy.suboptimal_flops = "deny"
clippy.uninlined_format_args = "allow"
clippy.unnecessary_self_imports = "deny"
clippy.unneeded_field_pattern = "deny"
clippy.unnested_or_patterns = "deny"
clippy.unused_trait_names = "deny"

rust.unfulfilled_lint_expectations = "deny"
